---
title: "R Notebook"
output: html_notebook
---

```{r setup}

knitr::opts_chunk$set(
  echo=TRUE,
  warning = TRUE,
  error = TRUE,
  message = TRUE,
  dev = 'svg'
  )

library(dplyr)
library(readr)
library(purrr)
library(tidyr)
library(lubridate)

#devtools::install_github('govdatascience/govstyle')
library(govstyle)
```

```{r}

member_files <- list.files('data', full.names = TRUE)

member_files
```

```{r}

members_df <- member_files %>% 
  map_df(~ read_csv(file = .x), .id = 'file') %>%
  mutate(file = member_files[as.integer(file)]) %>%
  separate(
    col = file, 
    sep = 'data\\/|\\.', 
    into = c('root', 'date', 'csv'),
    remove = TRUE
    ) %>%
  select(-root,-csv) %>%
  dplyr::mutate(
    date = ymd(date)
    )

members_df
  
```
Now try to separate the emails into department

```{r, fig.height=12, fig.width=6}

library(ggplot2)

members_df %>%
  separate(
    col = email,
    into = c('name', 'domain'),
    sep = '\\@'
    ) %>%
  group_by(date, domain) %>%
  tally %>%
  arrange(desc(n)) %>%
  ggplot +
  aes(
    x = reorder(domain, n),
    y = n
    ) +
  geom_bar(
    stat = 'identity',
    fill = gov_cols[1]
    ) +
  coord_flip() +
  facet_wrap(~date) +
  xlab('Domain') +
  theme_gov()

```

```{r}
sessionInfo()
```